name: ci

# https://dev.to/cicirello/jacoco-coverage-badges-pr-coverage-checks-and-pr-coverage-comments-from-github-actions-4a8f

on:
  push:
    branches: [ dev ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/badges/**.svg'
  pull_request:
    branches: [ dev ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/badges/**.svg'

jobs:
  test:
    timeout-minutes: 15

    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'Merge remote-tracking branch') }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Print Gradle version
        run: gradle --version

      - name: Print Java version
        run: java -version

      - name: Print Kotlin version
        run:  kotlinc -version

      - name: Run unit tests
        run: gradle test --tests "*"

          #/_test.sh
          #chmod +x ./_test.sh
          #./_test.sh
          #gradle clean build jacocoTestReport
          #gradle build jacocoTestReport
          #cat build/reports/jacoco/test/jacocoTestReport.csv


      - name: "JaCoCo: Generate badge"
        if: matrix.os == 'ubuntu-latest'
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.5.0
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          generate-branches-badge: true

      - name: "JaCoCo: Log coverage percentage"
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'commit badge'
          new_branch: 'jacoco'
          add: '*.svg'

#      - name: "JaCoCo: Commit the badge (if it changed)"
#        if: matrix.os == 'ubuntu-latest'
#        run: |
#          cd .github/badges
#          if [[ `git status --porcelain *.svg` ]]; then
#            git config --global user.name 'github-actions'
#            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
#            # cwd is .github/badges
#            git add *.svg
#            git commit -m "Autogenerated JaCoCo coverage badge" *.svg
#            git push
#          fi


  to-staging:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge current -> staging
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: staging
          github_token: ${{ github.token }}

