name: ci

# https://dev.to/cicirello/jacoco-coverage-badges-pr-coverage-checks-and-pr-coverage-comments-from-github-actions-4a8f

on:
  push:
    branches: [ dev ]
    paths-ignore:
      - '**.md'
      - '**.txt'
  pull_request:
    branches: [ dev ]
    paths-ignore:
      - '**.md'
      - '**.txt'

jobs:
  test:
    timeout-minutes: 15

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Print Gradle version
        run: gradle --version

      - name: Print Java version
        run: java -version

      - name: Print Kotlin version
        run:  kotlinc -version

      - name: Run unit tests
        run: |
          gradle clean build jacocoTestReport
          #chmod +x ./_test.sh
          #./_test.sh

      - name: "JaCoCo: Generate badge"
        if: matrix.os == 'ubuntu-latest'
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.0.1
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          generate-branches-badge: true

      - name: "JaCoCo: Log coverage percentage"
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"       

      - name: "JaCoCo: Commit the badge (if it changed)"
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd .github/badges
          if [[ `git status --porcelain *.svg` ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add *.svg
            git commit -m "Autogenerated JaCoCo coverage badge" *.svg
            git push
          fi          
          #if [[ `git status --porcelain` ]]; then
          #  git config --global user.name 'ArtÑ‘m IG'
          #  git config --global user.email 'rtmigo@users.noreply.github.com'
          #  git add -A
          #  git commit -m "Autogenerated JaCoCo coverage badge"
          #  git push
          #fi          


  to-staging:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge current -> staging
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: staging
          github_token: ${{ github.token }}

